# Generated by Django 5.1.1 on 2024-10-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('alert_type', models.CharField(max_length=100)),
                ('threshold', models.FloatField()),
                ('user_email', models.EmailField(max_length=254)),
                ('temperature', models.FloatField()),
                ('condition', models.CharField(max_length=255)),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('air_pressure', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
