# Generated by Django 5.1.1 on 2024-10-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_alter_weatheralert_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatheralert',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
