# Generated by Django 5.1.1 on 2024-10-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_alter_weatheralert_humidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatheralert',
            name='air_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weatheralert',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
