# Generated by Django 5.1.1 on 2024-10-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0004_alter_weatheralert_air_pressure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('temperature', models.FloatField()),
                ('condition', models.CharField(max_length=255)),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('air_pressure', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='weatheralert',
            name='air_pressure',
        ),
        migrations.RemoveField(
            model_name='weatheralert',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='weatheralert',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='weatheralert',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='weatheralert',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='weatheralert',
            name='wind_speed',
        ),
    ]
