# Generated by Django 5.0.6 on 2024-11-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0006_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
    ]
